// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozokmlmntjelodkdoopx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96b2ttbG1udGplbG9ka2Rvb3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Nzc0NTcsImV4cCI6MjA1OTQ1MzQ1N30.xEZjFXNBadgauP6-ieOm15Zei5vBhPk3DBnUN1E6ojM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export const saveOrderToSupabase = async (orderData: {
  order_id: string;
  user_id: string;
  items: any[];
  total_payment: number;
}) => {
  try {
    const { data, error } = await supabase
      .from('orders')
      .insert([
        {
          order_id: orderData.order_id,
          user_id: orderData.user_id,
          items: orderData.items,
          total_payment: orderData.total_payment
        }
      ]);

    if (error) {
      console.error('Error saving order to Supabase:', error);
      throw error;
    }

    return data;
  } catch (error) {
    console.error('Error in saveOrderToSupabase:', error);
    throw error;
  }
};